### ISSUE TITLE
Add Flake9

### ISSUE THREAD

**Issue by retnikt** [carlosperate/awesome-pyproject#23]
I have created [Flake9](https://gitlab.com/retnikt/flake9), a fork of [Flake8](https://gitlab.com/PyCQA/flake8) (who [refused](https://gitlab.com/PyCQA/flake8/-/issues/428) to implement it) that supports reading configuration from `pyproject.toml` files. Is it worth adding here?

**Comment by carlosperate** [comment]
Oh that's great, would you like to create a PR?
