### ISSUE TITLE
Suggest to remove PyOxidizer

### ISSUE THREAD

**Issue by layday** [carlosperate/awesome-pyproject#5]
The issue you link to discusses supporting PEP 517 build tools, not for PyOxidizer itself to become configurable through `pyproject.toml`.

**Comment by carlosperate** [comment]
But if implemented it would be able to read the pyproject.toml file to configure dependencies, no?
In that case I think it should still be included as they would still support the file format in a way.

**Comment by layday** [comment]
Not quite.  PyOxidizer does not configure Python dependencies.  It's the build tool that would be reading pyproject.toml; this might be poetry or flit or [enscons](https://pypi.org/project/enscons/) or what have you.
