### ISSUE TITLE
flake8-pyproject : a plugin for flake8 that forces flake8 to get its config from pyproject.toml

### ISSUE THREAD

**Issue by pepoluan** [carlosperate/awesome-pyproject#66]
PyPI : https://pypi.org/project/Flake8-pyproject/

GitHub : https://github.com/john-hen/Flake8-pyproject

I think this is more worthy of being mentioned in the page than "flake9", as flake8-pyproject is still under active development while flake9 seems to have died...

**Comment by carlosperate** [comment]
Oh, that's great, thanks!
Would you like to create a PR to remove flake9 and add flake8-pyproject?

**Comment by carlosperate** [comment]
Awesome, thanks!
